spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
    active: dev

  mvc:
    static-path-pattern: /**

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hzc.demo.pojo
  configuration:
    map-underscore-to-camel-case: true